### ISSUE TITLE
Ensure that each project in the DCP has an associated matrix

### ISSUE THREAD

**Issue by maniarathi** [HumanCellAtlas/dcp-prototype#87]
Each project needs a matrix that will be downloadable by the DCP 2.0 browser.

Acceptance Criteria
- [ ] Matrices are created for each of the 29 projects.
- [ ] Matrices are uploaded to each corresponding S3 bucket.
- [ ] Matrices are connected to each existing dataset's metadata graph either programmatically or manually.
- [ ] Matrices have the metadata fields described in the DCP 2.0 metadata schema.

**Comment by maniarathi** [comment]
Blocked by two issues that are generating the existing metadata structure for each project though the generation of the matrices can happen in parallel.

**Comment by mweiden** [comment]
@maniarathi do we have matrices for all 29 projects or is this also blocked by wranglers being able to run pipelines as well?

**Comment by maniarathi** [comment]
We have matrices for 13. There's an open question about whether for M1, we expect all 29 to have matrices or just the same 13 as the ones from DCP 1.0.

**Comment by ambrosejcarr** [comment]
Obtaining all 29 matrices requires wranglers being able to get matrices from users. The assays that don't have matrices are for the most part from assays for which we do not have standard pipelines.

**Comment by maniarathi** [comment]
@ambrosejcarr Makes sense. I see that there's a note in requirement 8 of M1 that:

"Jason and Ambrose are going to work up a transition plan for datasets that lack DCP-generated analysis results. During the pre-2.0 maintenance mode, wranglers will go back to contributors and request their published results and host those at the DCP in lieu of harmonized analysis. If count matrices are still unavailable for one or more datasets, we will revisit this problem at that time."

Does this mean that this ticket is blocked by wranglers fetching user-contributed matrices (needs to be created)? This is something that seems like it should be worked on right away then.

**Comment by ambrosejcarr** [comment]
Yes, this ticket is blocked on #90. 

I want for the system to go live with zero projects lacking count matrices. However, the prioritization should be done by @jahilton and @brianraymor . 

There's an added complexity around #90, which is that EBI are working on gathering some of these matrices from the original contributors. @jahilton how did your plans change in light of that learning from last week's call?

**Comment by maniarathi** [comment]
Got it. One more question for @ambrosejcarr and @mckinsel : in the requirements, it states that the matrices need to be available in a few different formats. Would you prefer that we simply store all formats of the matrix (convert them offline) or would you prefer an on-demand conversion from loom (if that is possible)?

**Comment by parthshahva** [comment]
For now, we only need to store the loom files from DCP 1.0. This will be passed along in the artifact. The browser ETL job is handling the conversion to other necessary downloadable formats.

Eventually, we need to start storing the expression data in the cell part of the schema/ledger. Especially once we start accepting user generated matrices. The artifact builder can then compose a matrix at the necessarily granularity for consumption by cellxgene and browser. This is especially important once cellxgene comes on board and requires additional matrix features such as embeddings.

**Comment by jahilton** [comment]
This task will be done independent of EBI's effort. I just created #112 for this task.

**Comment by maniarathi** [comment]
Given that this effort is being tracked elsewhere and the matrices for the demo have already been created by Marcus, closing.
